framework:
    router:
        strict_requirements: ~
#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
#    prefix:   /{_locale}
#easy_admin_bundle:
#    resource: "@EasyAdminBundle/Controller/AdminController.php"
#    type:     annotation
#    prefix:   /admin