swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    transport: smtp
    host:      smtp.mailtrap.io
    username:  3708bc2d54e01b
    password:  c42b8bbb9d73e0
    auth_mode: cram-md5
    port: 2525
