# See https://symfony.com/doc/current/email/dev_environment.html
#swiftmailer:
#    url: '%env(MAILER_URL)%'
swiftmailer:
    spool: { type: 'memory' }
    transport: smtp
    host:      smtp.mailtrap.io
    username:  3708bc2d54e01b
    password:  c42b8bbb9d73e0
    auth_mode: cram-md5
    port: 2525
#     send all emails to a specific address
#    delivery_addresses: ['virginija.prasmickaite@gmail.com']
